apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: tuan-ticketing-app-xyz-tls
spec:
  secretName: tuan-ticketing-app-xyz
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: tuan-ticketing-app.xyz
  dnsNames:
    - tuan-ticketing-app.xyz
    - www.tuan-ticketing-app.xyz
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - tuan-ticketing-app.xyz
          - www.tuan-ticketing-app.xyz